#+title: Clefd

A universal keybindings manager daemon.

** Usage
=clefd= is a universal keybindings daemon that reacts to input events by executing commands. It reads in a configuration file located at ~$XDG_CONFIG_HOME/clefd/clefdrc~ by default. Here the user can define a series of bindings that correspond to different commands.

*** Example Configuration

#+begin_example
# Launch a browser.
Super_L + w : firefox

# Take a screenshot.
Print : flameshot gui

# Launch tmux session.
Super_L + Shift_L + Return : tmux
#+end_example

*** Modifiers
=clefd= allows you to chain multiple modifier keys together. It supports the following XKB modifiers:
#+begin_example
Shift_L        /* Left shift */
Shift_R        /* Right shift */
Control_L      /* Left control */
Control_R      /* Right control */
Caps_Lock      /* Caps lock */
Shift_Lock     /* Shift lock */

Meta_L         /* Left meta */
Meta_R         /* Right meta */
Alt_L          /* Left alt */
Alt_R          /* Right alt */
Super_L        /* Left super */
Super_R        /* Right super */
Hyper_L        /* Left hyper */
Hyper_R        /* Right hyper */
#+end_example

*** Other Key Names
For a comprehensive list of XKB key names, please refer to the [[https://xkbcommon.org/doc/current/xkbcommon-keysyms_8h.html][libxkbcommon docs]]. Note that you will need to omit the =XKB_KEY_= prefix when adding these to your user configuration, e.g. =XKB_KEY_Escape= becomes =Escape=.

** Installation
*** Building From Source
#+begin_src sh
  git clone https://github.com/nshan651/clefd.git
  cd clefd
  sudo make install
#+end_src

If you are using systemd, start the service with ~systemctl --user enable --now clefd.service~

Additionally, you will require =libinput=, =libudev=, and =libxkbcommon= as runtime dependencies.

#+begin_src sh
  # Debian
  sudo apt install libinput10 libudev1 libxkbcommon0

  # Arch
  sudo pacman -S libinput systemd-libs libxkbcommon
#+end_src


Alternatively, you can use the ~guix.scm~ manifest file to create an interactive shell.

#+begin_src sh
  guix shell -m guix.scm
#+end_src
